'use client';

import { Controller, UseFormReturn } from 'react-hook-form';
import { Phone } from 'lucide-react';
import { FormField, FormItem, FormLabel, FormControl, FormMessage } from '@/components/ui/form';
import { Input } from '@/components/ui/input';
import { PhoneCodeInput } from '../reusable-components';
import { ClientFormData } from '../../validations/clients.schema';

interface ContactStepProps {
  form: UseFormReturn<ClientFormData>;
  isSecondary?: boolean;
  contactIndex: number;
}

export function ContactStep({ form, isSecondary = false, contactIndex }: ContactStepProps) {
  const title = isSecondary ? 'Contacto secundario (opcional)' : 'Contacto principal';
  const clientType = form.watch('clientType');
  const clientName = form.watch('name');

  // Para Persona Natural, el contacto principal es automático
  const isAutoGenerated = !isSecondary && clientType === 'PersonaNatural';

  return (
    <div className="space-y-6">
      <div className="text-center">
        <div className="mx-auto w-12 h-12 bg-primary/10 rounded-full flex items-center justify-center mb-4">
          <Phone className="h-6 w-6 text-primary" />
        </div>
        <h3 className="text-lg font-medium">{title}</h3>
        {isAutoGenerated && (
          <p className="text-sm text-muted-foreground mt-2">
            El nombre y rol se completan automáticamente. Solo necesitas proporcionar el número de teléfono (requerido) y el email (opcional).
          </p>
        )}
      </div>

      <div className="grid grid-cols-2 gap-4">
        <FormField
          control={form.control}
          name={`contacts.${contactIndex}.name` as const}
          render={({ field }) => (
            <FormItem>
              <FormLabel>Nombre del contacto</FormLabel>
              <FormControl>
                <Input
                  placeholder={isAutoGenerated ? clientName || "Nombre completo" : "Nombre completo"}
                  {...field}
                  value={field.value || (isAutoGenerated ? clientName : '')}
                  disabled={isAutoGenerated}
                />
              </FormControl>
              <FormMessage />
            </FormItem>
          )}
        />
        <FormField
          control={form.control}
          name={`contacts.${contactIndex}.role` as const}
          render={({ field }) => (
            <FormItem>
              <FormLabel>Rol/Cargo</FormLabel>
              <FormControl>
                <Input
                  placeholder={isAutoGenerated ? "Cliente Principal" : "Gerente, Dueño, etc."}
                  {...field}
                  value={field.value || (isAutoGenerated ? "Cliente Principal" : '')}
                  disabled={isAutoGenerated}
                />
              </FormControl>
              <FormMessage />
            </FormItem>
          )}
        />
      </div>

      <FormField
        control={form.control}
        name={`contacts.${contactIndex}.email` as const}
        render={({ field }) => (
          <FormItem>
            <FormLabel>Email {isAutoGenerated && '(Opcional)'}</FormLabel>
            <FormControl>
              <Input
                type="email"
                placeholder={isAutoGenerated ? "Opcional: email@ejemplo.com" : "email@ejemplo.com"}
                {...field}
                value={field.value || ''}
              />
            </FormControl>
            <FormMessage />
          </FormItem>
        )}
      />

      <Controller
        name={`contacts.${contactIndex}.phone` as const}
        control={form.control}
        render={({ field }) => (
          <FormItem>
            <FormLabel>Número de teléfono {!isAutoGenerated && '(Requerido)'}</FormLabel>
            <PhoneCodeInput
              value={field.value || ''}
              onChange={field.onChange}
              countryId={form.watch(`contacts.${contactIndex}.phoneCountryId` as const)}
              onCountryChange={(countryId) => {
                form.setValue(`contacts.${contactIndex}.phoneCountryId` as const, countryId);
              }}
            />
          </FormItem>
        )}
      />
    </div>
  );
}